routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** Rotas públicas */
Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@index');

    Route::get('donwload/{path}', 'PublicationsController@download')->name('public.publications.download');
    Route::get('publicacao/{id}', 'PublicationsController@show')->name('public.publication.show');

    Route::group(['prefix' => 'pesquisar'], function() {
        Route::get('autores', 'HomeController@searchByAuthor')->name('public.search.authors');
        Route::get('orientadores', 'HomeController@searchByAdvisor')->name('public.search.advisors');
        Route::get('titulos', 'HomeController@searchByTitle')->name('public.search.titles');
        Route::get('datas', 'HomeController@searchByDate')->name('public.search.dates');
    });
});

/** Rotas administrativas */
Route::group([
    'prefix' => 'administracao',
    'namespace' => 'Admin',
    'middleware' => ['auth'] /** linha da autenticação | apenas usuários logados podem acessar o admin */
], function () {
    Route::get('/', 'AdminController@index');
    Route::resource('arquivos', 'PublicationFilesController');
    Route::resource('publicacoes', 'PublicationsController');
    
    Route::group(['prefix' => 'cadastros'], function () {
        Route::resource('areas-de-conhecimento', 'KnowledgeAreasController');
        Route::resource('tipos-de-publicacao', 'PublicationTypesController');
        Route::resource('assuntos', 'SubjectsController');
        Route::resource('orientadores', 'AdvisorsController');
        Route::resource('autores', 'AuthorsController');
        Route::resource('usuarios', 'UsersController');
    });
});

Auth::routes();

/** Fix Temporário */
Route::get('/register', function() { return redirect('/'); });

app/Models/Publication.php
<?php

namespace Virtlib\Models;

use Illuminate\Database\Eloquent\Model;

class Publication extends Model
{
    protected $fillable = [
        'title', 'year', 'summary'
    ];

    // Autor
    public function author()
    {
        return $this->belongsTo(Author::class);
    }

    // Orientador
    public function advisor()
    {
        return $this->belongsTo(Advisor::class);
    }

    // Tipo da publicação
    public function type()
    {
        return $this->belongsTo(PublicationType::class, 'type_id');
    }

    // Área de conhecimento
    public function knowledgeArea()
    {
        return $this->belongsTo(KnowledgeArea::class, 'area_id');
    }

    // Arquivos "pdf's" correspondentes
    // Máximo de 3 por publicação 
    public function files()
    {
        return $this->hasMany(PublicationFile::class);
    }

    public function subjects()
    {
        return $this->belongsToMany(Subject::class);
    }
}

app/Models/PublicationType.php
<?php

namespace Virtlib\Models;

use Illuminate\Database\Eloquent\Model;

class PublicationType extends Model
{
    protected $fillable = ['name', 'status'];
    
    public function publications()
    {
        return $this->hasMany(Publication::class, 'type_id');
    }
}

app/Http/Controllers/Admin/PublicationsController.php
<?php

namespace Virtlib\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Virtlib\Http\Controllers\Controller;

use Virtlib\Repositories\Interfaces\PublicationRepositoryInterface;
use Virtlib\Repositories\Interfaces\PublicationTypeRepositoryInterface;
use Virtlib\Repositories\Interfaces\SubjectRepositoryInterface;
use Virtlib\Repositories\Interfaces\KnowledgeAreaRepositoryInterface;
use Virtlib\Repositories\Interfaces\AuthorRepositoryInterface;
use Virtlib\Repositories\Interfaces\AdvisorRepositoryInterface;

class PublicationsController extends Controller
{
    protected $repository;
    protected $subject;
    protected $knowledge_area;
    protected $publication_type;
    protected $author;
    protected $advisor;

    public function __construct(
        PublicationRepositoryInterface $repository,
        SubjectRepositoryInterface $subject,
        KnowledgeAreaRepositoryInterface $knowledge_area,
        PublicationTypeRepositoryInterface $publication_type,
        AuthorRepositoryInterface $author,
        AdvisorRepositoryInterface $advisor
    )
    {
        $this->repository = $repository;
        $this->subject = $subject;
        $this->knowledge_area = $knowledge_area;
        $this->publication_type = $publication_type;
        $this->author = $author;
        $this->advisor = $advisor;
    }

    public function index(Request $request)
    {
        if ( $request->has('modelo') && $request->has('id') ) {
            $model = $request->input('modelo');
            $id = $request->input('id');
            $publications = $this->repository->findByModelAndId($model, $id);
        } else {
            $publications = $this->repository->listAll();
        }
        
        return view('admin.publications.index', compact('publications'));
    }

    public function show($id)
    {
        $publication = $this->repository->findById( $id );

        if ( $publication )
        {
            $publication->author = $publication->author->name;
            if ( $publication->advisor ) $publication->advisor = $publication->advisor->name;
            $publication->knowledgeArea = $publication->knowledgeArea->name;
            $publication->type = $publication->type->name;
            $publication->files = $publication->files;

            $subjects = [];
            foreach( $publication->subjects as $subject ){
                $subjects[] = $subject->name;
            }

            $publication->subjects = $subjects;
        }

        return $publication;
    }

    public function create()
    {
        $subjects = $this->subject->listAll();
        $knowledge_areas = $this->knowledge_area->listAll();
        $publication_types = $this->publication_type->listAll();
        $authors = $this->author->listAll();
        $advisors = $this->advisor->listAll();

        return view('admin.publications.create', compact(
            'subjects',
            'knowledge_areas',
            'publication_types',
            'authors',
            'advisors'
        ));
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required|string|max:255',
            'author' => 'required',
            'year' => 'required',
        ]);
        
        if ( $this->repository->create($request->all()) ) {
            return response()->json([
                'status' => 'success',
                'msg' => 'Publicação adicionada com sucesso a base de dados'
            ], 200);
        } else {
            return response()->json([
                'status' => 'error',
                'msg' => 'Ocorreu algum problema. Tente novamente em alguns instantes.'
            ], 400);
        }
    }

    public function edit($id) {
        $publication = $this->repository->findById($id);
        $subjects = $this->subject->listAll();
        $knowledge_areas = $this->knowledge_area->listAll();
        $publication_types = $this->publication_type->listAll();
        $authors = $this->author->listAll();
        $advisors = $this->advisor->listAll();

        return view('admin.publications.edit', compact(
            'publication',
            'subjects',
            'knowledge_areas',
            'publication_types',
            'authors',
            'advisors'
        ));
    }

    public function update(Request $request, $id) {
        try {
            $this->repository->update($id, $request->all());
            return response()->json([
                'status' => 'success',
                'msg' => 'Publicação atualizada com sucesso'
            ], 200);
        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error',
                'msg' => 'Ocorreu algum problema. Tente novamente em alguns instantes.'
            ], 400);
        }
    }

    public function destroy($id)
    {
        $this->repository->delete( $id );
        return response()->json([
            'status' => 'success',
            'msg' => 'Publicação deletada com sucesso'
        ], 200);
    }
}

app/Http/Controllers/Front/PublicationsController.php
<?php

namespace Virtlib\Http\Controllers\Front;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Storage;
use Virtlib\Http\Controllers\Controller;
use Virtlib\Repositories\Interfaces\PublicationRepositoryInterface;

use Virtlib\Models\PublicationType;
use Virtlib\Models\KnowledgeArea;

class PublicationsController extends Controller
{
    protected $repository;

    public function __construct(PublicationRepositoryInterface $repository)
    {
        $this->repository = $repository;
        View::share('publication_types', PublicationType::all());
        View::share('knowledge_areas', KnowledgeArea::all());
    }

    public function download($path)
    {
        $file = 'publicacoes/' . $path;
        return Storage::download($file);
    }

    public function show( $id )
    {
        $publication = $this->repository->findById( $id );
        return view('front.show', compact('publication'));
    }
}

resources/views/admin/publications/create.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/administracao">Administração</a></li>
            <li class="breadcrumb-item"><a href="{{ route('publicacoes.index') }}">Publicações</a></li>
            <li class="breadcrumb-item active" aria-current="page">Adição de nova publicação</li>
        </ol>
    </nav>
@endsection

@section('content')
    <h3 class="page-title">
        <b>Adicionar Nova Publicação ao Acervo</b>
    </h3>

    <div class="card" style="margin-top: 12px;">
        <form id="form-publication" action="{{ route('publicacoes.store') }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="card-body">
                <div class="form-group">
                    <label for="title">Título</label>
                    <input class="form-control" name="title" id="title" required>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="author">Autor</label>
                            <select class="form-control" name="author" id="author" required>
                                <option></option>
                                @foreach ($authors as $author)
                                    <option value="{{ $author->id }}">{{ $author->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="advisor">Orientador</label>
                            <select class="form-control" name="advisor" id="advisor">
                                <option value="n/i"></option>
                                @foreach ($advisors as $advisor)
                                    <option value="{{ $advisor->id }}">{{ $advisor->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="knowledge-area">Área de Conhecimento</label>
                            <select class="form-control" name="knowledge_area" id="knowledge-area" required>
                                <option></option>
                                @foreach ($knowledge_areas as $area)
                                    <option value="{{ $area->id }}">{{ $area->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="publication-type">Tipo de Publicação</label>
                            <select class="form-control" name="publication_type" id="publication-type" required>
                                <option></option>
                                @foreach ($publication_types as $type)
                                    <option value="{{ $type->id }}">{{ $type->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="year">Ano</label>
                            <input type="number" min="0" xlength="" class="form-control" name="year" id="year" required>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card card-body" style="margin-top:30px;max-height: 24.1em;overflow-y: scroll;">
                            @foreach ($subjects as $subject)
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="subjects[]" value="{{ $subject->id }}" id="subject-{{ $subject->id }}">
                                    <label class="form-check-label" for="subject-{{ $subject->id }}">
                                        {{ $subject->name }}
                                    </label>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="editor">Resumo da publicação</label>
                    <textarea class="form-control" id="edito" name="summary"></textarea>
                </div>

                <div class="form-group">
                    <label class="control-label">Selecione os Arquivos da Publicação</label>
                    <input id="files" name="files[]" type="file" multiple>
                </div>

                <div class="card-footer text-right">
                    <button type="button" class="btn btn-danger"
                            onclick="javascript:document.location.href='{{ route('publicacoes.index') }}'">
                        Cancelar
                    </button>
                    <button type="submit" class="btn btn-success">Adicionar Publicação</button>
                </div>
            </div>
        </form>
    </div>
@stop

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link href="{{ asset('css/select2-bootstrap4.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="http://cdn.jsdelivr.net/npm/jquery-easy-loading/dist/jquery.loading.min.css">
    <link href="{{ asset('css/fileinput.css') }}" rel="stylesheet" />
@endsection

@section('js')
    <script src="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="{{ asset('js/fileinput.min.js') }}"></script>
    <script src="{{ asset('themes/fas/theme.js') }}"></script>
    <script src="{{ asset('js/locales/pt-BR.js') }}"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-beta.1/classic/ckeditor.js"></script>
    <script src="{{ asset('js/controllers/publications.js') }}"></script>
    <script>
        $('select').select2({
            theme: "bootstrap4"
        });

        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );

        $("#files").fileinput({
            theme: "fas",
            language: 'pt-BR',
            showUpload: false,
            dropZoneEnabled: false,
            allowedFileExtensions: ["pdf"],
            maxFileCount: 3
        });
    </script>
@endsection

resources/views/admin/publications/edit.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/administracao">Administração</a></li>
            <li class="breadcrumb-item"><a href="{{ route('publicacoes.index') }}">Publicações</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edição</li>
        </ol>
    </nav>
@endsection

@section('content')
    <h3 class="page-title">
        <b>Editar Publicação "{{ $publication->title }}"</b>
    </h3>

    <div class="card" style="margin-top: 12px;">
        <form id="form-publication" action="{{ route('publicacoes.update', ['id' => $publication->id]) }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="card-body">
                <div class="form-group">
                    <label for="title">Título</label>
                    <input class="form-control" name="title" id="title" value="{{ $publication->title }}">
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="author">Autor</label>
                            <select class="form-control" name="author" id="author">
                                <option></option>
                                @foreach ($authors as $author)
                                    <option value="{{ $author->id }}" @if($publication->author->id === $author->id) selected @endif>{{ $author->name }} {{ $author->last_name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="advisor">Orientador</label>
                            <select class="form-control" name="advisor" id="advisor">
                                <option value="n/i"></option>
                                @foreach ($advisors as $advisor)
                                    <option value="{{ $advisor->id }}" @if(($publication->advisor) && ($publication->advisor->id === $advisor->id)) selected @endif>{{ $advisor->name }} {{ $advisor->last_name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="knowledge-area">Área de Conhecimento</label>
                            <select class="form-control" name="knowledge_area" id="knowledge-area">
                                <option>Selecione...</option>
                                @foreach ($knowledge_areas as $area)
                                    <option value="{{ $area->id }}" @if($publication->knowledgeArea->id === $area->id) selected @endif>{{ $area->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="publication-type">Tipo de Publicação</label>
                            <select class="form-control" name="publication_type" id="publication-type">
                                <option>Selecione...</option>
                                @foreach ($publication_types as $type)
                                    <option value="{{ $type->id }}" @if($publication->type->id === $type->id) selected @endif>{{ $type->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="year">Ano</label>
                            <input type="number" min="0" xlength="" class="form-control" name="year" value="{{ $publication->year }}" id="year">
                        </div>
                    </div>
                    <div class="col">
                        <div class="card card-body" style="margin-top:30px;max-height: 24.1em;overflow-y: scroll;">
                            @foreach ($subjects as $subject)
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="subjects[]" value="{{ $subject->id }}" id="subject-{{ $subject->id }}"
                                    @if( in_array($subject->id, $publication->subjects()->pluck('subject_id')->all()) ) checked @endif>
                                    <label class="form-check-label" for="subject-{{ $subject->id }}">
                                        {{ $subject->name }}
                                    </label>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="editor">Resumo da publicação</label>
                    <textarea class="form-control" id="edito" name="summary">{{ $publication->summary }}</textarea>
                </div>

                @if ( (count($publication->files) - 3) )
                    <div class="form-group">
                        <label class="control-label">Selecione os Arquivos da Publicação</label>
                        <input id="files" name="files[]" type="file" multiple>
                    </div>
                @endif

                <div class="card card-body">
                    <table class="table table-sm table-bordered">
                        <thead class="bg-dark" style="color: whitesmoke;">
                            <tr>
                                <th colspan="2" class="text-center">Arquivos associados</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($publication->files as $file)
                            <tr>
                                <td>
                                    <b>{{ $file->name }}</b>
                                </td>
                                <td class="text-center" style="width: 80px;">
                                    <button type="button" class="btn btn-sm btn-danger"
                                            onclick="publicationFileDelete({{ $file->id }})">
                                        <i class="fa fa-fw fa-trash">&nbsp;</i> deletar
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

                <div class="card-footer text-right">
                    <button type="button" class="btn btn-danger"
                            onclick="javascript:document.location.href='{{ route('publicacoes.index') }}'">
                        Cancelar
                    </button>
                    <button type="submit" class="btn btn-success">Atualizar Publicação</button>
                </div>
            </div>
        </form>

        @include('admin.publications.includes.delete-publication-file-form')
    </div>
@stop

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link href="{{ asset('css/select2-bootstrap4.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="http://cdn.jsdelivr.net/npm/jquery-easy-loading/dist/jquery.loading.min.css">
    <link href="{{ asset('css/fileinput.css') }}" rel="stylesheet" />
@endsection

@section('js')
    <script src="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="{{ asset('js/fileinput.min.js') }}"></script>
    <script src="{{ asset('themes/fas/theme.js') }}"></script>
    <script src="{{ asset('js/locales/pt-BR.js') }}"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-beta.1/classic/ckeditor.js"></script>
    <script src="{{ asset('js/controllers/publications.js') }}"></script>
    <script>
        $('select').select2({
            theme: "bootstrap4"
        });

        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );

        $("#files").fileinput({
            theme: "fas",
            language: 'pt-BR',
            showUpload: false,
            dropZoneEnabled: false,
            allowedFileExtensions: ["pdf"],
            maxFileCount: 3
        });
    </script>
@endsection

resources/views/admin/publications/index.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Administração</a></li>
            <li class="breadcrumb-item active" aria-current="page">Publicações</li>
        </ol>
    </nav>
@endsection

@section('content')
    <h3 class="page-title">
        <b>Lista de Publicacoes</b>
    </h3>

    <br />

    <div class="row">
        <div class="col">
            <table id="table-publications" class="table table-sm table-bordered">
                <thead>
                <tr>
                    <th>Título</th>
                    <th>Autor</th>
                    <th>Ano</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($publications as $publication)
                    <tr id="publication-{{ $publication->id }}">
                        <td>{{ $publication->title }}</td>
                        <td>{{ $publication->author->name }}</td>
                        <td width="50px">{{ $publication->year }}</td>
                        <td class="text-center" width="170px;">
                            <a role="button" class="btn btn-sm btn-warning"
                               href="{{ route('publicacoes.edit', ['id' => $publication->id]) }}">
                                <i class="fa fa-fw fa-edit"></i>
                            </a>

                            <button class="btn btn-sm btn-info"
                                    onclick="publicationShow({{ $publication->id }})">
                                <i class="fa fa-fw fa-eye"></i>
                            </button>

                            <button class="btn btn-sm btn-danger"
                                    onclick="publicationDelete({{ $publication->id }})">
                                <i class="fa fa-fw fa-trash"></i>
                                deletar
                            </button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

    @include('admin.publications.includes.delete-publication-form')
    @include('admin.publications.includes.show-modal')
@stop

@section('css')
    <link rel="stylesheet" href="http://cdn.jsdelivr.net/npm/jquery-easy-loading/dist/jquery.loading.min.css">
@stop

@section('js')
    <script src="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.js"></script>
    <script src="{{ asset('js/controllers/publications.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#table-publications').DataTable({
                "language": {
                    "url": "http://cdn.datatables.net/plug-ins/1.10.16/i18n/Portuguese-Brasil.json"
                },
            });
        } );
    </script>
@stop