routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** Rotas públicas */
Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@index');

    Route::get('donwload/{path}', 'PublicationsController@download')->name('public.publications.download');
    Route::get('publicacao/{id}', 'PublicationsController@show')->name('public.publication.show');

    Route::group(['prefix' => 'pesquisar'], function() {
        Route::get('autores', 'HomeController@searchByAuthor')->name('public.search.authors');
        Route::get('orientadores', 'HomeController@searchByAdvisor')->name('public.search.advisors');
        Route::get('titulos', 'HomeController@searchByTitle')->name('public.search.titles');
        Route::get('datas', 'HomeController@searchByDate')->name('public.search.dates');
    });
});

/** Rotas administrativas */
Route::group([
    'prefix' => 'administracao',
    'namespace' => 'Admin',
    'middleware' => ['auth'] /** linha da autenticação | apenas usuários logados podem acessar o admin */
], function () {
    Route::get('/', 'AdminController@index');
    Route::resource('arquivos', 'PublicationFilesController');
    Route::resource('publicacoes', 'PublicationsController');
    
    Route::group(['prefix' => 'cadastros'], function () {
        Route::resource('areas-de-conhecimento', 'KnowledgeAreasController');
        Route::resource('tipos-de-publicacao', 'PublicationTypesController');
        Route::resource('assuntos', 'SubjectsController');
        Route::resource('orientadores', 'AdvisorsController');
        Route::resource('autores', 'AuthorsController');
        Route::resource('usuarios', 'UsersController');
    });
});

Auth::routes();

/** Fix Temporário */
Route::get('/register', function() { return redirect('/'); });

app/Models/KnowledgeArea.php
<?php

namespace Virtlib\Models;

use Illuminate\Database\Eloquent\Model;

class KnowledgeArea extends Model
{
    protected $fillable = ['name', 'status'];
    
    public function publications()
    {
        return $this->hasMany(Publication::class, 'area_id');
    }
}

app/Http/Controllers/Admin/KnowledgeAreasController.php
<?php

namespace Virtlib\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Virtlib\Http\Controllers\Controller;
use Virtlib\Repositories\Interfaces\KnowledgeAreaRepositoryInterface;

class KnowledgeAreasController extends Controller
{
    protected $repository;

    public function __construct(KnowledgeAreaRepositoryInterface $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        $knowledge_areas = $this->repository->listAll();
        return view('admin.support.knowledge_areas.index', compact('knowledge_areas'));
    }

    public function create(Request $request)
    {
        return view('admin.support.knowledge_areas.create');
    }

    public function store(Request $request)
    {
        $inputs = $request->validate([
            'name' => 'required|string|max:255'
        ]);

        $knowledge_areas = $this->repository->create( $inputs );

        return response()->json([
                    "message" => "Registro inserido no banco com sucesso!"
                ],200);
    }

    public function edit($id)
    {
        return $this->repository->findById($id);
    }

    public function update(Request $request, $id)
    {
        try {
            $this->repository->update($id, $request->all());
            return response()->json([
                'type' => 'success',
                'msg' => 'Registro atualizado com sucesso!'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'type' => 'error',
                'msg' => 'Ocorreu um erro. Tente novamente em alguns instantes.'
            ], 400);
        }
    }

    public function destroy($id)
    {
        if ( $this->repository->delete($id) ) 
        {
            return response()->json([
                'type' => 'success',
                'msg' => 'Registro atualizado com sucesso!'
            ]);
        } else {
            return response()->json([
                'type' => 'error',
                'msg' => 'Ocorreu um erro. Tente novamente em alguns instantes.'
            ], 400);
        }
    }
}

resources/views/admin/support/knowledge_areas/index.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/administracao">Administração</a></li>
            <li class="breadcrumb-item active" aria-current="page">Áreas de Conhecimento</li>
        </ol>
    </nav>
@endsection

@section('content')
<h3 class="page-title">
    <b>Lista de Áreas de Conhecimento</b>
</h3>

<div class="card custom-box" style="margin-bottom: 12px;">
    <div class="card-body text-right">
        <form id="form-new-knowledge_area" action="{{ route('areas-de-conhecimento.store') }}" method="POST">
            {{ csrf_field() }}
            <div class="form-row">
                <div class="col-7">
                    <input type="text" class="form-control rounded-0" placeholder="Área de Conhecimento" name="name" required>
                </div>
                <div class="col">
                    <button id="btn-add" type="submit" class="btn btn-block bg-custom-red rounded-0">
                        Adicionar Área de Conhecimento
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col">
        <table id="table-knowledge_areas" class="table table-sm table-bordered">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th class="text-center">Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach($knowledge_areas as $knowledge_area)
                    <tr id="knowledge_area-{{ $knowledge_area->id }}">
                        <td>{{ $knowledge_area->name }}</td>
                        <td class="text-center" width="65px;">
                            @if ( count($knowledge_area->publications ) )
                                <a href="{{ route('publicacoes.index') }}?modelo=area&id={{ $knowledge_area->id}}" class="custom-link-total">
                                    {{ count( $knowledge_area->publications ) }}
                                </a>
                            @else
                                N/I
                            @endif
                        </td>
                        <td class="text-center" width="170px;">
                            <button class="btn btn-sm btn-warning"
                                onclick="knowledge_areaEdit({{ $knowledge_area->id }})">
                                <i class="fa fa-fw fa-edit"></i>
                                editar
                            </button>
                            
                            <button class="btn btn-sm btn-danger"
                                onclick="knowledge_areaDelete({{ $knowledge_area->id }})">
                                <i class="fa fa-fw fa-trash"></i>
                                deletar
                            </button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

@include('admin.support.knowledge_areas.includes.edit-modal')
@include('admin.support.knowledge_areas.includes.delete-knowledge_area-form')

@stop 

@section('css')
    <link rel="stylesheet" href="http://cdn.jsdelivr.net/npm/jquery-easy-loading/dist/jquery.loading.min.css">
@stop

@section('js')
    <script>
        $(document).ready(function() {
            $('#table-knowledge_areas').DataTable({
                "language": {
                    "url": "http://cdn.datatables.net/plug-ins/1.10.16/i18n/Portuguese-Brasil.json"
                },
            });
        } );
    </script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.js"></script>
    <script src="{{ asset('js/controllers/knowledge-areas.js') }}"></script>
@stop